[package]
name = "linear-sdk"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
graphql_client = { version = "0.14.0", features = ["reqwest"] }
reqwest = { version = "0.12.18", features = ["json"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.45.1", features = ["full"] }

[build-dependencies]
graphql_client_codegen = "0.14.0"
